export const PARAM_FINGERPRINT = "PARAM_FINGERPRINT";

export const PARAM_UPDATE_PACKS = "PARAM_UPDATE_PACKS";

export const PARAM_CLIENT_PRIVATE_KEY = "PARAM_CLIENT_PRIVATE_KEY";
export const PARAM_CLIENT_PUBLIC_KEY = "PARAM_CLIENT_PUBLIC_KEY";

export const PARAM_REMOTE_STORAGE_LAST_UPDATE_TIME = "PARAM_REMOTE_STORAGE_LAST_UPDATE_TIME";
export const PARAM_REMOTE_STORAGE_VALUES = "PARAM_REMOTE_STORAGE_VALUES";
export const PARAM_REMOTE_STORAGE_VALUES_TO_SAVE = "PARAM_REMOTE_STORAGE_VALUES_TO_SAVE";
export const PARAM_REMOTE_STORAGE_IDENTIFIERS_TO_DELETE = "PARAM_REMOTE_STORAGE_IDENTIFIERS_TO_DELETE";
