export const PARAM_FINGERPRINT = "PARAM_FINGERPRINT";

export const PARAM_UPDATE_PACKS = "PARAM_UPDATE_PACKS";

export const PARAM_CLIENT_PRIVATE_KEY = "PARAM_CLIENT_PRIVATE_KEY";
export const PARAM_CLIENT_PUBLIC_KEY = "PARAM_CLIENT_PUBLIC_KEY";
